baseURL: "https://shantanu96.github.io/"
languageCode: "en-us"
title: "Shantanu Bhosale"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio"
  description: My Portfolio
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Shantanu Bhosale" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Shantanu."
    subtitle: "I build things for the web"
    content: "A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
    image: /images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1Rg_E57ITrXi6yde1MYkMbCf4D1KQC8vQ/view?usp=drive_link"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/shantanu-bhosale-939229144/
        - icon: fab fa-github
          url: https://github.com/shantanu96

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/photo.png"
    content: |-
      I am a software developer with a 3+ years of work experience in Web, Microservice and Cloud. I have expertise in Spring Boot, Docker, Kubernetes, Azure DevOps and AWS. I like to work on new ideas and solve real world problems. I am currently working as a software developer at [Crisil Limited.](https://www.crisil.com/) in Mumbai, India. 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Spring Boot"
        - "JPA"
        - "Spring Security"
        - "Express JS"
        - "MySQL"
        - "Azure DevOps"
        - "Kong"
        - "Docker"
        - "AWS"
        - "Kubernetes"
        - "Helm Charts"
        - "Vault"
        - "Keycloak"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Engineer"
        company: "Crisil"
        companyUrl: "https://www.crisil.com/"
        date: "August 2021 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        # content: "I am currently working as a Software Engineer at [Crisil Limited.](https://www.crisil.com/) in Mumbai, India. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "Intern"
        company: "Crisil"
        companyUrl: "https://www.crisil.com/"
        date: "Jan 2021 - July 2021"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"

      - job: "Full Stack Intern"
        company: "BITGENIE"
        companyUrl: "https://www.instagram.com/bitgenieresearch/"
        date: "April 2020 - July 2020"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"

      - job: "Software Developer"
        company: "NEUROLINX SOFTWARE"
        # companyUrl: ""
        date: "Sept 2017 - Dec 2017"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"

  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Business Administration"
        school:
          name: "K.J. Somaiya Institute of Management"
          url: "https://kjsim.somaiya.edu/en/"
        date: "2018 - 2021"
        # GPA: "3.8 out of 5.0"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: BitsyUrl
        content: URL Management site allowing you to save bookmarks, create short URLs and get analytics.
        image: /images/bitsyurl.png
        featured:
          name: Website
          link: https://bitsyurl.in/
        badges:
          - "Express JS"
          - "Javascript"
          - "MongoDB"
          - "Alpine JS"
      - title: Evaluation
        content: 'Price Evaluation app for Owned Bikes which will be used by dealers to capture vehicle details. 
        The system wil try to evaluate the price of the vehicle based on the past records.'
        image: /images/everi.png
        badges:
          - "Freelannce"
          - "Spring Boot"
          - "Spring Security"
          - "JPA"
          - "MySQL"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    email: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:shantanubhosale96@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/shantanu96
      linkedin: https://www.linkedin.com/in/shantanu-bhosale-939229144/
      twitter: https://twitter.com/shantanu363

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>